# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 20e5a8a89d3afd86d74b2c3121d8e4881b1ce896a3e9b06d788712fce6a2ab5bd9c2e8b71a91ca7f081e06c60e3d36101fa134c112a128aea1aff770e09d4e4b

test:
  secret_key_base: 20dcd3312913d55574a8eef9474266352ff50b4835bc677b7db64bafb1266c46ff72de5e11c643f5058dda7f495001dc34f04964ecd2431a4293d10b78d3703a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
